src/Entity/JobCron.php
<?php

namespace App\Entity;
use Cron\CronExpression;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\JobCronRepository;
/**
 * @ORM\Entity(repositoryClass=JobCronRepository::class)
 */
class JobCron extends Job
{


    /**
     * @ORM\Column(type="string")
     */
     private $scriptExec;


     /**
      * @ORM\OneToMany(targetEntity=Historique::class, mappedBy="jobCronHist")
      */
     private $historiques;

    /**
     * @ORM\Column(type="string")
     */
    private $expression;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\JobComposite" , inversedBy="historiqueSousJob")
     */
    private $relationHistJobComp;

    /**
     * @ORM\ManyToMany(targetEntity=JobComposite::class, mappedBy="listSousJobs")
     */
    private $jobComposites;

    /**
     * @ORM\ManyToMany(targetEntity=Admin::class, inversedBy="jobCronCreated")
     */
    private $listDesination;

    /**
     * @ORM\Column(type="boolean")
     */
    public $actif;


    /**
     * @ORM\Column(type="string")
     */
    private $state;

    /**
     * @ORM\Column(type="integer",unique=true)
     */
    private $numero;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $emailadmincron;

    /**
     * @return mixed
     */
    public function getActif()
    {
        return $this->actif;
    }

    /**
     * @param mixed $actif
     * @return JobCron
     */
    public function setActif($actif)
    {
        $this->actif = $actif;
        return $this;
    }




    /**
     * @return mixed
     */
    public function getExpression()
    {
        return $this->expression;
    }

    /**
     * @param mixed $expression
     * @return JobCron
     */
    public function setExpression($expression)
    {
        $this->expression = $expression;
        return $this;
    }

     public function __construct()
     {
         $this->historiques = new ArrayCollection();
         $this->jobComposites = new ArrayCollection();
         $this->listDesination = new ArrayCollection();
     }

    /**
     * @return mixed
     */




     /**
      * @return Collection<int, Historique>
      */
     public function getHistoriques(): Collection
     {
         return $this->historiques;
     }

     public function addHistorique(Historique $historique): self
     {
         if (!$this->historiques->contains($historique)) {
             $this->historiques[] = $historique;
             $historique->setJobCronHist($this);
         }

         return $this;
     }

    /**
     * @return mixed
     */
    public function getScriptExec()
    {
        return $this->scriptExec;
    }

    /**
     * @param mixed $scriptExec
     * @return JobCron
     */
    public function setScriptExec($scriptExec)
    {
        $this->scriptExec = $scriptExec;
        return $this;
    }

     public function removeHistorique(Historique $historique): self
     {
         if ($this->historiques->removeElement($historique)) {
             // set the owning side to null (unless already changed)
             if ($historique->getJobCronHist() === $this) {
                 $historique->setJobCronHist(null);
             }
         }

         return $this;
     }

     public function __toString()
     {
         return $this->getScriptExec();
     }






    public function getRelationHistJobComp(): Collection
    {
        return $this->relationHistJobComp;
    }

    /**
     * @param mixed $relationHistJobComp
     * @return JobCron
     */
    public function setRelationHistJobComp($relationHistJobComp)
    {
        $this->relationHistJobComp = $relationHistJobComp;
        return $this;
    }

    /**
     * @return Collection<int, JobComposite>
     */
    public function getJobComposites(): Collection
    {
        return $this->jobComposites;
    }

    public function addJobComposite(JobComposite $jobComposite): self
    {
        if (!$this->jobComposites->contains($jobComposite)) {
            $this->jobComposites[] = $jobComposite;
            $jobComposite->addListSousJob($this);
        }

        return $this;
    }

    public function removeJobComposite(JobComposite $jobComposite): self
    {
        if ($this->jobComposites->removeElement($jobComposite)) {
            $jobComposite->removeListSousJob($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Admin>
     */
    public function getListDesination(): Collection
    {
        return $this->listDesination;
    }

    public function addListDesination(Admin $listDesination): self
    {
        if (!$this->listDesination->contains($listDesination)) {
            $this->listDesination[] = $listDesination;
        }

        return $this;
    }

    public function removeListDesination(Admin $listDesination): self
    {
        $this->listDesination->removeElement($listDesination);

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function nextDateCron(string $expression){

        $cron = new CronExpression($expression);
        return $cron->getNextRunDate()->format('i G j n w');
    }

    public function getNumero(): ?int
    {
        return $this->numero;
    }

    public function setNumero(int $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getEmailadmincron(): ?string
    {
        return $this->emailadmincron;
    }

    public function setEmailadmincron(string $emailadmincron): self
    {
        $this->emailadmincron = $emailadmincron;

        return $this;
    }



}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface,\Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function serialize()
    {
        return serialize([
           $this->id,
            $this->username,
            $this->password
        ]);
    }

    public function unserialize($serialize)
    {
        list($this->id,$this->username,$this->password) = unserialize($serialize,['allowed_classes'=>false]);
    }

    public function getRoles()
    {
        return ['ROLE_ADMIN'];
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }
}

src/Form/JobCronType.php
<?php

namespace App\Form;

use App\Entity\Admin;
use App\Entity\JobCron;
use Doctrine\DBAL\Types\BooleanType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class JobCronType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('code',TextType::class)
            ->add('name',TextType::class, ['required'=>false])
            ->add('expression', TextType::class,['required'=>false])
            ->add('state',TextType::class,['required'=>false])
            ->add('actif',TextType::class,['required'=>false])
            //->add('listDestination',EntityType::class,['class' => Admin::class,'multiple'=>true])
            ->add('createdBy', EntityType::class, ['class' => Admin::class, 'choice_label' => 'name' ])
//            ->add('nextDateExec',DateTimeType::class,['required'=>false])
            ->add('scriptExec',TextType::class)

        ;
    }
    public function configureOptions(OptionsResolver $resolver)
    {
       $resolver->setDefaults([
           'data_class' => JobCron::class,
       ]);
    }


}

src/Controller/JobCronController.php
<?php
namespace App\Controller;
use App\Entity\JobCron;
use App\Entity\JobCronSearch;
use App\Form\CreateNewJobCronType;
use App\Form\EditJobCronType;
use App\Form\JobCronSearchType;
use App\Message\LogCommand;
use App\Repository\HistoriqueRepository;
use App\Repository\JobCronRepository;
use Cron\CronExpression;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\KernelInterface;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @Route("/admin/job/cron")
 */
class JobCronController extends AbstractController
{
    private $jobCronRepo;
    private $manager;
    private $bus;
    private $security;
    public function __construct(JobCronRepository $jobCronRepo,EntityManagerInterface $manager,MessageBusInterface  $bus,Security $security)
    {
        $this->jobCronRepo = $jobCronRepo;
        $this->manager = $manager;
        $this->bus = $bus;
        $this->security = $security;
    }


    /**
     * @Route("/", name="app_jobCron_index", methods={"GET"})
     */
    public function index(PaginatorInterface $paginator,JobCronRepository $jobCronRepository, Request $request): Response
    {
        $search = new JobCronSearch();
        $form = $this->createForm(JobCronSearchType::class,$search);
        $form->handleRequest($request);

        $jobCron = $paginator->paginate($jobCronRepository->findSpecific($search), $request->query->getInt('page',1),4);


        return $this->render('JobCron/index.html.twig', [
            'jobCron' => $jobCron,
            'form'=> $form->createView()
        ]);
    }

    /**
     * @Route("/new", name="app_jobCron_new", methods={"GET", "POST"})
     */
    public function new(Request $request, JobCronRepository $jobCronRepository,UserInterface $user): Response
    {
        $jobCron = new JobCron();
        $form = $this->createForm(CreateNewJobCronType::class, $jobCron);
        $form->handleRequest($request);

        $jobCron->setState("NOUVEAU");
        $jobCron->setActif(1);
        $jobCron->setCode(uniqid());

       // $user = $this->getUser()->getUsername();

        $jobCron->setEmailadmincron($user->getUsername());

        if ($form->isSubmitted() && $form->isValid()) {
            $jobCronRepository->add($jobCron);

            return $this->redirectToRoute('app_jobCron_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('JobCron/new.html.twig', [
            'admin' => $jobCron,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_JobCron_show", methods={"GET"})
     */
    public function show(JobCron $jobCron): Response
    {
       // $jobCron = $this->jobCronRepo->findElementById('secondJobCron');
        return $this->render('JobCron/show.html.twig', [
            'JobCron' => $jobCron,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_JobCron_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, JobCron $jobCron, JobCronRepository $repository): Response
    {

        $form = $this->createForm(EditJobCronType::class, $jobCron);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em=$this->manager;
            $em->persist($jobCron);
            $em->flush();
            $this->addFlash('success',"un job cron a ete modifié avec succes");


            return $this->redirectToRoute('app_jobCron_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('JobCron/edit.html.twig', [
            'JobCron' => $jobCron,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/{id}/delete", name="app_JobCron_delete", methods={"GET","POST"})
     */
    public function delete(Request $request, JobCron $jobCron, JobCronRepository $jobCronRepository): Response
    {
         if($jobCron->getJobComposites()->toArray()==[]) {
             $jobCronRepository->remove($jobCron);
         }
         else{

         }

        return $this->redirectToRoute('app_jobCron_index', [], Response::HTTP_SEE_OTHER);
        //return new Response(implode() );

    }


    /**
     * @Route("/{id}/execImme", name="app_JobCron_execute" , methods={"GET","POST"})
     */
    public function execImm(KernelInterface $kernel,JobCron $jobCron){
//        $jobCron->setState("en cours");
//        $this->manager->persist($jobCron);
//        $this->manager->flush();
//        $application = new Application($kernel);
//        $application->setAutoExit(false);
//        $input = new ArrayInput(array(
//            'command' => $jobCron->getScriptExec(),
//            'Related_job'=>$jobCron->getId()
//        ));
//
//        // Use the NullOutput class instead of BufferedOutput.
//        $output = new BufferedOutput();
//
//        $application->run($input, $output);
//
//        $content = $output->fetch();
//        $pr = new Process(sprintf('php bin/console %s %s',  $jobCron->getScriptExec(),$jobCron->getId()));
//        $pr->setWorkingDirectory(__DIR__ . '/../..');
//
//        $pr->start();
//        while ($pr->isRunning()) {
//            $jobCron->setState("en cours");
//            $this->manager->persist($jobCron);
//            $this->manager->flush();
//
//        }
        //envoyer la demande de lancement du job au RabbitMq
        $message = new LogCommand($jobCron->getScriptExec(),$jobCron->getId(),"0","0");
        $this->bus->dispatch($message);
        //changement de l'état du job en lui affectant la valeur "en cours"
        $jobCron->setState("en cours");
        //persistance des changements dans la base de données
        $this->manager->persist($jobCron);
        $this->manager->flush();
        //création d'un instance historique relative au lancement immédiat du job

        return $this->redirectToRoute('app_jobCron_index', [], Response::HTTP_SEE_OTHER);

    }



    /**
     * @Route("/{id}/downloadFile", name="app_JobCron_downloadFiles" ,methods={"GET"})
     */
    public function download(JobCron $jobCron,HistoriqueRepository $repository,KernelInterface $kernel){

        $historique = $repository->findByExampleField($jobCron);

        return $this->file($kernel->getProjectDir().max($historique)->getPath());
    }


    /**
     * @Route("/{id}/actifdesactif", name="app_JobCron_actifdesactif",methods={"GET","PUT"})
     */
    public function actifdesactif(JobCron $jobCron,EntityManagerInterface $manager){
        if($jobCron->getActif()){
            $jobCron->setActif(false);
            $manager->persist($jobCron);
            $manager->flush();
        }
        else{
            $jobCron->setActif(true);
            $manager->persist($jobCron);
            $manager->flush();
        }
        return $this->redirectToRoute('app_jobCron_index', [], Response::HTTP_SEE_OTHER);
    }




    /**
     * @Route("/{id}/date/",name="app_JobCron_date" , methods={"GET"})
     */
    public function giveDate(JobCronRepository $repository){
        return new Response($repository->giveDateTime());
    }

    /**
     * @Route("/{id}/nextDate/",name="app_JobCron_nextdate",methods={"GET"})
     */
    public function nextDate(JobCronRepository $repository){
        $jobCron = $repository->findElementById(13);
        $cron = new CronExpression($jobCron->getExpression());
//        return new Response($cron->getNextRunDate()->format('i G j n w'));
        echo date('i G j n w', strtotime('+1 minute'));
        echo $cron->getNextRunDate()->format('i G j n w');
        echo get_debug_type($cron->getNextRunDate()->format('i G j n w'));
        return new Response(date('i G j n w', strtotime('+1 minute'))==$cron->getNextRunDate()->format('i G j n w') ? 'yes':'no');

    }


}

templates/JobCron/new.html.twig
{#{% extends 'base.html.twig' %}#}

{#{% block title %}New JobCron{% endblock %}#}

{#{% block body %}#}
{#    <h1>Create new JobCron</h1>#}

{#    {{ include('JobCron/_formCreate.html.twig') }}#}

{#    <a href="{{ path('app_jobCron_index') }}">back to list</a>#}
{#{% endblock %}#}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><meta name="description" content=""><meta name="author" content="">
    <title>Page d'accueil</title>
    <!-- Custom fonts for this template-->
    <link href="../public/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="{{ asset('vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="{{ asset('css/sb-admin-2.min.css') }}" rel="stylesheet">
</head>
<body id="page-top">
<!-- Page Wrapper -->
<div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ path('Home') }}">

            <div class="sidebar-brand-text mx-3">Page d'accueil</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item ">
            <a class="nav-link" href="{{ path('Home') }}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
            Interface
        </div>

        <!-- Nav Item - Pages Collapse Menu -->
        {% if app.user.roles == ['ROLE_ADMIN', 'ROLE_SUPER_ADMIN'] %}
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
               aria-expanded="true" aria-controls="collapseTwo">
                <i class="fa fa-users"></i>
                <span>Admin</span>
            </a>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Custom Components:</h6>
                    <a class="collapse-item" href="{{ path('app_admin_index') }}">Administrateurs</a>
                    <a class="collapse-item" href="{{ path('app_admin_new') }}">Créer un Admin</a>
                </div>
            </div>
        </li>
        {% endif %}

        <!-- Nav Item - Utilities Collapse Menu -->
        <li class="nav-item active">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
               aria-expanded="true" aria-controls="collapseUtilities">
                <i class="fas fa-clock"></i>
                <span>Jobs</span>
            </a>
            <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                 data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Les jobs crons:</h6>
                    <a class="collapse-item" href="{{ path('app_jobCron_index') }}">Tous les jobs crons</a>
                    <a class="collapse-item" href="{{ path('app_jobCron_new') }}">Créer un job cron</a>

                    <h6 class="collapse-header">Les jobs composites:</h6>
                    <a class="collapse-item" href="{{ path('app_job_composite_index') }}">Tous les jobs composites</a>
                    <a class="collapse-item" href="{{ path('app_job_composite_new') }}">Créer un job composite</a>

                </div>
            </div>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->


        <!-- Nav Item - Pages Collapse Menu -->


        <!-- Nav Item - Charts -->


        <!-- Divider -->


        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

        <!-- Sidebar Message -->

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>

                <!-- Topbar Search -->
                <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                               aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>

                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">

                    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                    <li class="nav-item dropdown no-arrow d-sm-none">
                        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-search fa-fw"></i>
                        </a>
                        <!-- Dropdown - Messages -->
                        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                             aria-labelledby="searchDropdown">
                            <form class="form-inline mr-auto w-100 navbar-search">
                                <div class="input-group">
                                    <input type="text" class="form-control bg-light border-0 small"
                                           placeholder="Search for..." aria-label="Search"
                                           aria-describedby="basic-addon2">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="button">
                                            <i class="fas fa-search fa-sm"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </li>

                    <!-- Nav Item - Alerts -->
                    <li class="nav-item dropdown no-arrow mx-1">

                        <!-- Dropdown - Alerts -->

                    </li>

                    <!-- Nav Item - Messages -->
                    <li class="nav-item dropdown no-arrow mx-1">

                    </li>

                    <div class="topbar-divider d-none d-sm-block"></div>

                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="{{ path('login') }}" id="userDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ app.user ? app.user.username : 'anonymous'}}</span>
                            <img class="img-profile rounded-circle"
                                src="{{ asset('img/undraw_profile.svg') }}"

                            >

                        </a>
                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                             aria-labelledby="userDropdown">
                            <a class="dropdown-item" href="#">
                                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                Profile
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                Settings
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                Activity Log
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ path('logout') }}" data-toggle="modal" data-target="#logoutModal">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                Logout
                            </a>
                        </div>
                    </li>

                </ul>

            </nav>
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <h1 class="h3 mb-0 text-gray-800">Administrateurs</h1>
                </div>

                <!-- Content Row -->
                <div class="row">

                    <!-- Earnings (Monthly) Card Example -->


                    <!-- Earnings (Monthly) Card Example -->
                    {{ include('JobCron/_formCreate.html.twig') }}

                    <!-- Earnings (Monthly) Card Example -->


                    <!-- Pending Requests Card Example -->

                </div>

                <!-- Content Row -->

                <div class="row">

                    <!-- Area Chart -->

                    <!-- Pie Chart -->

                </div>

                <!-- Content Row -->
                <div class="row">

                    <!-- Content Column -->



                </div>

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        <!-- Footer -->

        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="{{ path('logout') }}">Logout</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- Core plugin JavaScript-->
<script src="{{ asset('vendor/jquery-easing/jquery.easing.min.js') }}"></script>

<!-- Custom scripts for all pages-->
<script src="{{ asset('js/sb-admin-2.min.js') }}"></script>

<!-- Page level plugins -->
<script src="{{ asset('vendor/chart.js/Chart.min.js') }}"></script>

<!-- Page level custom scripts -->

<script src="{{ asset('js/demo/chart-area-demo.js') }}"></script>
<script src="{{ asset('js/demo/chart-pie-demo.js') }}"></script>
</body>

</html>